#!/bin/bash
# Backup app forms and submissions - full or incremental
env=${1:-"local"}
echo $env
. config/env/$env.env

echo "Pull Forms and Submissions from Source system"
echo "** and save to backup directory **"

options=( "full", "incremental" )
PS3='Select backup type or 0 to exit: '
select mode in "${options[@]}"; do
    if [[ $REPLY == "0" ]]; then
        echo 'Bye!' >&2
        exit
    elif [[ -z $mode ]]; then
        echo 'Invalid choice, try again' >&2
    else
        break
    fi
done

source env/bin/activate --system-site-packages
python3 ./app/lib/backup_data.py $mode
